const ROUTES = {
  LOGIN: '/',
  DASHBORAD: '/dashboard',
  ACADEMIC: '/academic',
  YEAR: '/year',
  STUDENTREGISTRATION: '/studentRegistartion',
  ADDREGISTRATION: '/addRegistrationForm',
  FEEDESCRIPTION: '/feeDescription',
  ADDFEEDESCRIPTION: '/addFeeDescription',
  FEEMASTER: '/feeMaster',
  FEERECEIPT: '/feeReceipt',
  STUDENT_CONCESSION: '/studentConcession',
  CHANGE_STUDENT_FEE: '/changeStudentFee',
  FINANCE_CATEGORY: '/financeCategory',
  FINANCE_GROUP: '/financeGroupList',
  FINANCE_SUB_GROUP: '/financeSubGroupList',
  FINANCE_BANK_LIST: '/financeBankList',
  FINANCE_LEDGER_LIST: '/financeLedgerList',
  FINANCE_BILL_PAYMENT: '/financeBillPayment',
  FINANCE_APPLICATION_RECEIPT: '/applicationReceipt',
  ADD_RECEIPT: '/addReceipt',
  ADD_PAYMENT: '/addPayment',
  ADD_CONTRA: '/addContra',
  ADD_JOURNAL: '/addJournal',
  BALANCE_SHEET: '/BalanceSheet',
  ADD_ROLE: '/addRole',
  ADD_FEE_MASTER: '/addFeeMaster',
  LEAVE_MASTER:'/leaveMaster',
  ADD_LEAVE: '/addLeave'
}

export default ROUTES
